[tool:pytest]
addopts = 
    --strict-markers
    --strict-config
    --tb=short
    --color=yes
    -v
    --alluredir=allure-results
markers =
    smoke: Smoke tests
    regression: Regression tests
    navigation: Navigation tests
    ingredients: Ingredients tests
    orders: Order tests