[pytest]
addopts = -v --strict-markers --tb=short
markers =
    smoke: Smoke tests
    regression: Regression tests
    navigation: Navigation tests
    ingredients: Ingredients tests
    order_feed: Order feed tests
    user_actions: User actions tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*